export class Product {
    region: string = '';
    branch: string = '';
    application: string = '';
    machine_type: string = '';
    product: string = '';
    single_tandem: string = '';
    product_family: string= '';
    series: string = '';
    size_ccm: string = '';
    options: string = '';
    global_material: string = '';
    material_number: string = '';
    type_code: string = '';
    s3d_model_available: string = '';
    s3d_model_pdm: string = '';
    spare_parts: string = '';
    data_sheets: string = '';
    goto_express: string = '';
    s3dmap_id: any;
    quick_delivery_time: any;
    material_status: any;
    product_hier: any;
    status: boolean = false;
    ms: any;
    get_product_detailed: string = '';
    material: any;
    data: any;
    nofound: boolean = false;
    group1_name: string = '';
    group2_name: string = '';
    group3_name: string = '';
    selected_industrysector1: string = '';
    selected_industrysector2: string = '';
    selected_application: string = '';
}
