# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - angularapps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      
        
      # - name: proxy configuration
      #   run: npm config set proxy http://rb-proxy-de.bosch.com:8080;
      #        npm config set https-proxy http://rb-proxy-de.bosch.com:8080;
      #        npm config set strict-ssl=true;
       
      - name:  proxy configuration1
        run: npm config set proxy http://mac1ul:°!Sherlocked1998@rb-proxy-de.bosch.com:8080;
      - name:  proxy configuration2
        run: npm config set https-proxy http://mac1ul:°!Sherlocked1998@rb-proxy-de.bosch.com:8080;
      - name:  proxy configuration3
        run: npm config set strict-ssl=true;
           
      - name: check the config list
        run: npm config list

      - name: check proxy registry
        run:  npm config get registry

      - name: setting reg config
        run:  npm config set registry https://registry.npmjs.org/
        
      - name: refreshing npm installation
        run:  npm install @angular/common
       

      # - name: disable proxies
      #   run: npm config delete proxy
      #        npm config delete http-proxy
      #        npm config delete https-proxy

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
      - name: disable proxies
        run:  npm help config

       
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          
      - name: unzip artifact for deployment
        run: unzip -o release.zip
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'angularapps'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5CB1E652158D4E0E8EB03D9BBE16BC78 }}
          package: .
